version: "2" # required to adjust maintainability checks
checks:
  method-lines:
    config:
      threshold: 80

plugins:
  duplication:
    enabled: true
    exclude_patterns:
      - "**/*.spec.ts"
      - "**/*.spec.tsx"
